### ISSUE TITLE
Support VSCode Insider?

### ISSUE THREAD

**Issue by Tuizi** [hashhar/vscode-universal-installer#2]
It could be nice to support the Insider channel?

https://code.visualstudio.com/insiders

**Comment by hashhar** [comment]
I'll work on it. Thanks for the idea.

**Comment by hashhar** [comment]
@Tuizi Could you please check and see if you can download VSCode Insider release by clicking on all of the links below. I think the links are session generated and hence unique.

[Windows](https://az764295.vo.msecnd.net/insider/149e7a0debf3e32f95978a606e00d3c09bcac3d6/VSCodeSetup-insider.exe)

[Linux 32bit](https://az764295.vo.msecnd.net/insider/149e7a0debf3e32f95978a606e00d3c09bcac3d6/VSCode-linux-ia32-insider.zip)

[Linux 64bit](https://az764295.vo.msecnd.net/insider/149e7a0debf3e32f95978a606e00d3c09bcac3d6/VSCode-linux-x64-insider.zip)

[MacOSX](https://az764295.vo.msecnd.net/insider/45d69357c9eb068dd8e624f5b0fe461cd2078d88/VSCode-darwin-insider.zip)

**Comment by Tuizi** [comment]
All links work for me :+1: 

Windows ✔
Linux 32bit ✔
Linux 64bit ✔
MacOSX ✔

**Comment by hashhar** [comment]
Thanks. I'll add support for the Insider channel by tonight.
